#include <sys/types.h>
#include <sys/time.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <assert.h>
#include <zlib.h>

/* include main header file */
#include "mud.h"

//Skill Table
const struct skill_data skill_table[] =
{
  {SK_ANALYZE_MIXTURE		,"Analyze Mixture"				,-1},
  {SK_ANCIENT_LORE		,"Ancient Lore"					,-1},
  {SK_ART			,"Art"						,-1},
  {SK_CARTOGRAPHY		,"Cartography"					,-1},
  {SK_CHIROGRAPHY		,"Chirography"					,-1},
  {SK_DIPLOMACY			,"Diplomacy"					,-1},
  {SK_DRAFTING			,"Drafting"					,-1},
  {SK_HEALING_ARTS		,"Healing Arts"					,-1},
  {SK_HORTICULTURE		,"Horticulture"					,-1},
  {SK_INTERNAL_ALCHEMY		,"Internal Alchemy"				,SK_SPELL_CAST_MYSTICISM},
  {SK_INVENTING			,"Inventing"					,SK_DRAFTING},
  {SK_LINGUISTICS		,"Linguistics"					,-1},
  {SK_MUSIC			,"Music"					,-1},
  {SK_NATURALISM		,"Naturalism"					,-1},
  {SK_NAVIGATION		,"Navigation"					,-1},
  {SK_READ_MAGIC		,"Read Magic"					,-1},
  {SK_THEOLOGY			,"Theology"					,-1},
  {SK_BARTER			,"Barter"					,-1},
  {SK_BASIC_SEAMANSHIP		,"Basic Seamanship"				,-1},
  {SK_CRAFT_BREWING		,"Craft: Brewing"				,-1},
  {SK_CRAFT_COOKING		,"Craft: Cooking"				,-1},
  {SK_CRAFT_LEATHER_WORKING	,"Craft: Leather Working"			,-1},
  {SK_CRAFT_WOOD_WORKING	,"Craft: Wood Working"				,-1},
  {SK_CRAFT_ARMOR_SMITHING	,"Craft: Armor Smithing"			,-1},
  {SK_CRAFT_WEAPON_SMITHING	,"Craft: Weapon Smithing"			,-1},
  {SK_CRAFT_GARDENING		,"Craft: Gardening"				,-1},
  {SK_CRAFT_MASONRY		,"Craft: Masonry"				,-1},
  {SK_KNOWLEDGE_GENERAL_LORE	,"Knowledge: General Lore"			,-1},
  {SK_KNOWLEDGE_NATURE		,"Knowledge: Nature"				,-1},
  {SK_KNOWLEDGE_RELIGIOUS_LORE	,"Knowledge: Religious Lore"			,-1},
  {SK_KNOWLEDGE_ARCANE_LORE	,"Knowledge: Arcane Lore"			,-1},
  {SK_KNOWLEDGE_DEMON_LORE	,"Knowledge: Demon Lore"			,-1},
  {SK_KNOWLEDGE_GEOGRAPHY	,"Knowledge: Geography"				,-1},
  {SK_KNOWLEDGE_HISTORY		,"Knowledge: History"				,-1},
  {SK_KNOWLEDGE_DIVINE_LORE	,"Knowledge: Divine Lore"			,-1},
  {SK_DRINKING			,"Drinking"					,-1},
  {SK_GAMBLING			,"Gambling"					,-1},
  {SK_HAGGLING			,"Haggling"					,-1},
  {SK_LANGUAGE_CENTAUR		,"Language: Centaur"				,-1},
  {SK_LANGUAGE_COMMON		,"Language: Common"				,-1},
  {SK_LANGUAGE_DRUAS		,"Langauge: Druas"				,-1},
  {SK_LANGUAGE_DWARF		,"Language: Dwarf"				,-1},
  {SK_LANGUAGE_ELF		,"Language: Elf"				,-1},
  {SK_LANGUAGE_FERRAN		,"Language: Ferran"				,-1},
  {SK_LANGUAGE_GNOME		,"Language: Gnome"				,-1},
  {SK_LANGUAGE_HUMAN		,"Language: Human"				,-1},
  {SK_LANGUAGE_KOBOLD		,"Language: Kobold"				,-1},
  {SK_LANGUAGE_OGRE		,"Language: Ogre"				,-1},
  {SK_LANGUAGE_ORC		,"Language; Orc"				,-1},
  {SK_LANGUAGE_RAKASHAN		,"Language: Rakashan"				,-1},
  {SK_LANGUAGE_SAURIAN		,"Language: Saurian"				,-1},
  {SK_LANGUAGE_WOLFEN		,"Langauge: Wolfen"				,-1},
  {SK_LITERACY_CENTAUR		,"Literacy: Centaur"				,SK_LANGUAGE_CENTAUR},
  {SK_LITERACY_COMMON		,"Literacy: Common"				,SK_LANGUAGE_COMMON},
  {SK_LITERACY_DRUAS		,"Literacy: Druas"				,SK_LANGUAGE_DRUAS},
  {SK_LITERACY_DWARF		,"Literacy: Dwarf"				,SK_LANGUAGE_DWARF},
  {SK_LITERACY_ELF		,"Literacy: Elf"				,SK_LANGUAGE_ELF},
  {SK_LITERACY_FERRAN		,"Literacy: Ferran"				,SK_LANGUAGE_FERRAN},
  {SK_LITERACY_GNOME		,"Literacy: Gnome"				,SK_LANGUAGE_GNOME},
  {SK_LITERACY_HUMAN		,"Literacy: Human"				,SK_LANGUAGE_HUMAN},
  {SK_LITERACY_KOBOLD		,"Literacy: Kobold"				,SK_LANGUAGE_KOBOLD},
  {SK_LITERACY_OGRE		,"Literacy: Ogre"				,SK_LANGUAGE_OGRE},
  {SK_LITERACY_ORC		,"Literacy: Orc"				,SK_LANGUAGE_ORC},
  {SK_LITERACY_RAKASHAN		,"Literacy: Rakashan"				,SK_LANGUAGE_RAKASHAN},
  {SK_LITERACY_SAURIAN		,"Literacy: Saurian"				,SK_LANGUAGE_SAURIAN},
  {SK_LITERACY_WOLFEN		,"Literacy: Wolfen"				,SK_LANGUAGE_WOLFEN},
  {SK_RIDING			,"Riding"					,-1},
  {SK_SIGN			,"Sign"						,-1},
  {SK_STREETWISE		,"Streetwise"					,-1},
  {SK_SWIMMING			,"Swimming"					,-1},
  {SK_ARCHERY_I			,"Archery I"					,SK_WEAPON_PROF_BOW},
  {SK_ARCHERY_II		,"Archery II"					,SK_ARCHERY_I},
  {SK_BLIND_FIGHTING		,"Blind Fighting"				,-1},
  {SK_COMMAND			,"Command"					,-1},
  {SK_MARTIAL_ARTS_I		,"Martial Arts I"				,-1},
  {SK_MARTIAL_ARTS_II		,"Martial Arts II"				,SK_MARTIAL_ARTS_I},
  {SK_MOUNTED_COMBAT_I		,"Mounted Combat I"				,SK_RIDING},
  {SK_MOUNTED_COMBAT_II		,"Mounted Combat II"				,SK_MOUNTED_COMBAT_I},
  {SK_STREET_FIGHTING		,"Street Fighting"				,-1},
  {SK_WEAPON_PROF_BLOWGUN	,"Weapon Proficiency: Blowgun"			,-1},
  {SK_WEAPON_PROF_BLUNT		,"Weapon Proficiency: Blunt"			,-1},
  {SK_WEAPON_PROF_BOW		,"Weapon Proficiency: Bow"			,-1},
  {SK_WEAPON_PROF_CHAIN		,"Weapon Proficiency: Chain"			,-1},
  {SK_WEAPON_PROF_DAGGER_KNIFE	,"Weapon Proficiency: Dagger/Knife"		,-1},
  {SK_WEAPON_PROF_FORKED_TRIDENT,"Weapon Proficiency: Forked/Trident"		,-1},
  {SK_WEAPON_PROF_GRAPPLING_HOOK,"Weapon Proficiency: Grappling Hook"		,-1},
  {SK_WEAPON_PROF_MISSILE_WEAPONS,"Weapon Proficiency: Missile Weapons"		,-1},
  {SK_WEAPON_PROF_NET		,"Weapon Proficiency: Net"			,-1},
  {SK_WEAPON_PROF_PAIRED_WEAPONS,"Weapon Proficiency: Paired Weapons"		,-1},
  {SK_WEAPON_PROF_SHIELD	,"Weapon Proficiency: Shield"			,-1},
  {SK_WEAPON_PROF_SIEGE_WEAPONS	,"Weapon Proficiency: Siege Weapons"		,-1},
  {SK_WEAPON_PROF_SPEAR		,"Weapon Proficiency: Spear"			,-1},
  {SK_WEAPON_PROF_STAFF		,"Weapon Proficiency: Staff"			,-1},
  {SK_WEAPON_PROF_SWORD		,"Weapon Proficiency: Sword"			,-1},
  {SK_WEAPON_PROF_THROWING_WEAPONS,"Weapon Proficiency: Throwing Weapons"	,-1},
  {SK_WEAPON_PROF_WHIP		,"Weapon Proficiency: Whip"			,-1},
  {SK_WEAPON_SPEC_BLOWGUN       ,"Weapon Specialization: Blowgun"		,SK_WEAPON_PROF_BLOWGUN},
  {SK_WEAPON_SPEC_BLUNT         ,"Weapon Specialization: Blunt"			,SK_WEAPON_PROF_BLUNT},
  {SK_WEAPON_SPEC_BOW           ,"Weapon Specialization: Bow"			,SK_WEAPON_PROF_BOW},
  {SK_WEAPON_SPEC_CHAIN         ,"Weapon Specialization: Chain"			,SK_WEAPON_PROF_CHAIN},
  {SK_WEAPON_SPEC_DAGGER_KNIFE  ,"Weapon Specialization: Dagger/Knife"		,SK_WEAPON_PROF_DAGGER_KNIFE},
  {SK_WEAPON_SPEC_FORKED_TRIDENT,"Weapon Specialization: Forked/Trident"	,SK_WEAPON_PROF_FORKED_TRIDENT},
  {SK_WEAPON_SPEC_GRAPPLING_HOOK,"Weapon Specialization: Grappling Hook"	,SK_WEAPON_PROF_GRAPPLING_HOOK},
  {SK_WEAPON_SPEC_MISSILE_WEAPONS,"Weapon Specialization: Missile Weapons"	,SK_WEAPON_PROF_MISSILE_WEAPONS},
  {SK_WEAPON_SPEC_NET           ,"Weapon Specialization: Net"			,SK_WEAPON_PROF_NET},
  {SK_WEAPON_SPEC_PAIRED_WEAPONS,"Weapon Specialization: Paired Weapons"	,SK_WEAPON_PROF_PAIRED_WEAPONS},
  {SK_WEAPON_SPEC_SHIELD        ,"Weapon Specialization: Shield"		,SK_WEAPON_PROF_SHIELD},
  {SK_WEAPON_SPEC_SIEGE_WEAPONS ,"Weapon Specialization: Siege Weapons"		,SK_WEAPON_PROF_SIEGE_WEAPONS},
  {SK_WEAPON_SPEC_SPEAR         ,"Weapon Specialization: Spear"			,SK_WEAPON_PROF_SPEAR},
  {SK_WEAPON_SPEC_STAFF         ,"Weapon Specialization: Staff"			,SK_WEAPON_PROF_STAFF},
  {SK_WEAPON_SPEC_SWORD         ,"Weapon Specialization: Sword"			,SK_WEAPON_PROF_SWORD},
  {SK_WEAPON_SPEC_THROWING_WEAPONS,"Weapon Specialization: Throwing Weapons"	,SK_WEAPON_PROF_THROWING_WEAPONS},
  {SK_WEAPON_SPEC_WHIP          ,"Weapon Specialization: Whip"			,SK_WEAPON_PROF_WHIP},
  {SK_WRESTLING			,"Wrestling"					,-1},
  {SK_ZEN_ARCHERY		,"Zen Archery"					,SK_ARCHERY_II},
  {SK_BRAWLING			,"Brawling"					,-1},
  {SK_CLIMBING			,"Climbing"					,-1},
  {SK_FLOATING			,"Floating"					,-1},
  {SK_HIDING			,"Hiding"					,-1},
  {SK_LEAPING			,"Leaping"					,-1},
  {SK_MOVE_SILENTLY		,"Move Silently"				,-1},
  {SK_SEARCHING			,"Searching"					,-1},
  {SK_ACROBATICS_I		,"Acrobatics I"					,-1},
  {SK_ACROBATICS_II		,"Acrobatics II"				,SK_ACROBATICS_I},
  {SK_ACTING			,"Acting"					,-1},
  {SK_ANIIMAL_TRAINING		,"Animal Training"				,-1},
  {SK_JUGGLING			,"Juggling"					,-1},
  {SK_KNIFE_THROWING		,"Knife Throwing"				,-1},
  {SK_LEGERDEMAIN		,"Legerdemain"					,-1},
  {SK_ORATORY			,"Oratory"					,-1},
  {SK_SIDE_SHOW_TALENT		,"Side Show Talent"				,-1},
  {SK_ADV_ALCHEMICAL_EQUIPMENT	,"Advanced Alchemical Equipment"		,SK_ALCHEMICAL_DEVICES},
  {SK_ADV_ALCHEMICAL_SUBSTANCES	,"Advanced Alchemical Substances"		,SK_ADV_ALCHEMICAL_EQUIPMENT},
  {SK_ADV_NECROMANTIC_RITUALS	,"Advanced Necromantic Rituals"			,SK_NECROMANTIC_RITUALS},
  {SK_ADV_THAUMATURGICAL_EQUIPMENT,"Advanced Thaumaturgical Equipment"		,SK_LOCATE_RARE_EARTHS},
  {SK_ALCHEMICAL_DEVICES	,"Alchemical Devices"				,-1},
  {SK_ALCHEMICAL_DUSTS		,"Alchemical Dusts"				,SK_ALCHEMICAL_DEVICES},
  {SK_AQUA_VITAE_AND_HOMUNCULI	,"Aqua Vitae and Homunculi"			,SK_ADV_ALCHEMICAL_EQUIPMENT},
  {SK_ARMORED_SPELL_CASTING	,"Armored Spell Casting"			,-1},
  {SK_ARTIST			,"Artist"					,-1},
  {SK_ASSASSINATE		,"Assassinate"					,-1},
  {SK_BACKSTAB			,"Backstab"					,-1},
  {SK_CONVERT			,"Convert"					,-1},
  {SK_DETECT_CONJURATION	,"Detect Conjuration"				,-1},
  {SK_DETECT_ILLUSION		,"Detect Illusion"				,-1},
  {SK_ESSENCES			,"Essences"					,SK_ADV_THAUMATURGICAL_EQUIPMENT},
  {SK_EVOKER			,"Evoker"					,SK_KNOWLEDGE_DEMON_LORE},
  {SK_GOLEMS			,"Golems"					,-1},
  {SK_GREATER_MAGIC_ITEMS	,"Greater Magic Items"				,SK_MINOR_MAGIC_ITEMS},
  {SK_HERBAL_ELIXERS		,"Herbal Elixers"				,SK_HERBAL_REMEDIES},
  {SK_HERBAL_REMEDIES		,"Herbal Remedies"				,SK_ALCHEMICAL_DEVICES},
  {SK_HOLY_ITEMS		,"Holy Items"					,SK_SPELL_CAST_DIVINE_MAGIC},
  {SK_INFLUENCE_ANIMALS		,"Influence Animals"				,-1},
  {SK_INSCRIBE_SYMBOL		,"Inscribe Symbol"				,-1},
  {SK_JACK_OF_ALL_TRADES	,"Jack of All Trades"				,-1},
  {SK_LOCATE_RARE_EARTHS	,"Locate Rare Earths"				,-1},
  {SK_MACHINA			,"Machina"					,-1},
  {SK_MAGICAL_MIXTURES		,"Magical Mixtures"				,SK_ALCHEMICAL_DEVICES},
  {SK_MAGICAL_WEAPONS_AND_ARMOR	,"Magical Weapons and Armor"			,SK_GREATER_MAGIC_ITEMS},
  {SK_MANY_MASKS		,"Many Masks"					,-1},
  {SK_MINOR_MAGIC_ITEMS		,"Minor Magic Item"				,SK_SPELL_CAST_ENCHANTMENT},
  {SK_MUSCIAN			,"Musician"					,-1},
  {SK_NECROMANTIC_RITUALS	,"Necromantic Rituals"				,-1},
  {SK_OBSERVATORY		,"Observatory"					,-1},
  {SK_PASS_WITHOUT_TRACE	,"Pass Without Trace"				,-1},
  {SK_PATRON_OF_THE_LOWER_PLANES,"Patron of the Lower Planes"			,-1},
  {SK_PHILTRES			,"Philtres"					,SK_READ_MAGIC},
  {SK_POTIONS			,"Potions"					,SK_MAGICAL_MIXTURES},
  {SK_POWER_ANIMAL		,"Power Animal"					,-1},
  {SK_PROJECTION_OF_WILL	,"Projection of Will"				,-1},
  {SK_RODS_STAVES_WANDS		,"Rods, Staves, and Wands"			,SK_RUNES},
  {SK_RUNES			,"Runes"					,SK_INSCRIBE_SYMBOL},
  {SK_SCHOLARLY			,"Scholarly"					,-1},
  {SK_SCROLLS			,"Scrolls"					,SK_INSCRIBE_SYMBOL},
  {SK_SEE_INTO_SPIRIT_REALM	,"See Into Spirit Realm"			,-1},
  {SK_SHAPE_CHANGE_ANIMAL	,"Shape Change: Animal"				,-1},
  {SK_SPELL_CAST_ASTROLOGY	,"Spell Casting: Astrology"			,-1},
  {SK_SPELL_CAST_BLACK_MAGIC	,"Spell Casting: Black Magic"			,-1},
  {SK_SPELL_CAST_DIVINE_MAGIC	,"Spell Casting: Divine Magic"			,-1},
  {SK_SPELL_CAST_ELEMENTAL_MAGIC,"Spell Casting: Elemental Magic"		,-1},
  {SK_SPELL_CAST_ENCHANTMENT	,"Spell Casting: Enchantment"			,-1},
  {SK_SPELL_CAST_HIGH_MAGIC	,"Spell Casting: High Magic"			,-1},
  {SK_SPELL_CAST_LOW_MAGIC	,"Spell Casting: Low Magic"			,-1},
  {SK_SPELL_CAST_MYSTICISM	,"Spell Casting: Mysticism"			,-1},
  {SK_SPELL_CAST_SORCERY	,"Spell Casting: Sorcery"			,-1},
  {SK_SPIRIT_BINDING		,"Spirit Binding"				,-1},
  {SK_TOXIC_POWDERS		,"Toxic Powders"				,SK_ALCHEMICAL_DEVICES},
  {SK_TURN_UNDEAD		,"Turn Undead"					,-1},
  {SK_VENOMS_AND_POISONS	,"Venoms and Poisons"				,SK_ALCHEMICAL_DEVICES},
  {SK_WAYLAY			,"Waylay"					,-1},
  {SK_APPRAISE_TREASURE		,"Appraise Treasure"				,-1},
  {SK_CATWALK			,"Catwalk"					,-1},
  {SK_CON			,"Con"						,-1},
  {SK_DECIPHER			,"Decipher"					,-1},
  {SK_EVADE_PURSUIT		,"Evade Pursuit"				,-1},
  {SK_FORGERY			,"Forgery"					,-1},
  {SK_HIDE_IN_SHADOWS		,"Hide in Shadows"				,-1},
  {SK_INFILTRATE		,"Infiltrate"					,-1},
  {SK_INTERROGATE		,"Interrogation"				,-1},
  {SK_LIP_READING		,"Lip Reading"					,-1},
  {SK_LOCK_PICKING		,"Lock Picking"					,-1},
  {SK_PICK_POCKET		,"Pick Pocket"					,-1},
  {SK_SCALING_WALLS		,"Scaling Walls"				,-1},
  {SK_STEALTH			,"Stealth"					,-1},
  {SK_TAILING			,"Tailing"					,-1},
  {SK_THIEVES_CANT		,"Thieve's Cant"				,-1},
  {SK_TRAPS			,"Traps"					,-1},
  {SK_CAMOUFLAGE		,"Camouflage"					,-1},
  {SK_HERB_LORE			,"Herb Lore"					,-1},
  {SK_HUNTING			,"Hunting"					,-1},
  {SK_MOUNTAIN_CLIMBING		,"Mountain Climbing"				,-1},
  {SK_READ_TRACKS		,"Read Tracks"					,-1},
  {SK_SCOUTING			,"Scouting"					,SK_CAMOUFLAGE},
  {SK_SNARES			,"Snares"					,-1},
  {SK_STALKING			,"Stalking"					,-1},
  {SK_SURVIVAL			,"Survival"					,-1},
  {SK_TRACKING			,"Tracking"					,SK_READ_TRACKS},
  {0}
};

/*
 * find_skill()
 * Returns skill number based on name
 */
int find_skill(const char *name)
{
    int i;
    for (i = 0; i < SKILL_MAX; i++)
    {
        if (skill_table[i].name == NULL)
            break;
  	if (LOWER (name[0]) == LOWER (skill_table[i].name[0])
            && compares (name, skill_table[i].name))
            return i;
    }
    return 0;
}
